const NODE_WIDTH = 355;
const NODE_HEIGHT = 90;
const HEADER_MENU_WIDTH = 250;
const DEFAULT_MAP_NAME = 'Mapa sem nome';
const EXPORT_MAP_TIMEOUT = 500;

export {
  NODE_WIDTH,
  NODE_HEIGHT,
  HEADER_MENU_WIDTH,
  DEFAULT_MAP_NAME,
  EXPORT_MAP_TIMEOUT,
};
